Adds skeleton docs build
Pelagicore/software-factory pull request #1
Opened 2017-05-02 13:36 UTC by breakreturn

A minimal buildable setup with license info, build
instructions and contribution guide.

Signed-off-by: Joakim Gross <joakim.gross@pelagicore.com>

2017-05-02 13:57 UTC, frznlogic requested changes
Do we want to maintain a Vagrantfile as well for creating maintained build environments as well?

@jeremiah says; I would say yes! Definitely!

2017-05-02 13:57 UTC, frznlogic commented on scripts/publish_docs.sh
> +    echo "Aborting pulication of documentation due to the repository being 'dirty'"
pulication

2017-05-02 14:12 UTC, rpannek approved these changes

2017-05-02 14:27 UTC, DunderRoffe approved these changes
Using CMake seems overkill but it looks fine

2017-05-02 15:21 UTC, jeremiah commented on scripts/publish_docs.sh
> +    echo "Aborting pulication of documentation due to the repository being 'dirty'"
I got pulicated!

2017-05-02 15:22 UTC, jeremiah approved these changes
* I'm missing a definition of what SWF is for a potential user who has never heard the name before.
* I added some boilerplate and a date to the README

2017-05-02 19:04 UTC, DunderRoffe commented
As discussed offline, using pure Sphinx or python might be an alternative to cmake.
In the Sphinx documentation they refer to building using the following command in bash:

```bash
$ sphinx-build -b html sourcedir builddir
```
http://www.sphinx-doc.org/en/stable/tutorial.html

2017-05-03 06:44 UTC, breakreturn commented
I personally feel that a VM is overkill for this build. There are no tests or other activities that would make a common environment beneficial, and the dependencies are quite reasonable for developers of this to have installed. I don't foresee any issues with the CI machines lacking the dependencies either. Perhaps we can have a VM as an improvement in the future if we see a need for it?

2017-05-03 06:49 UTC, breakreturn commented
Yes, I just reused previous stuff and based it on CMake for no good reason I think. I agree pure Python would be easier. Can we treat that as a future improvement as well?

2017-05-03 06:54 UTC, erikboto commented on README.md
> +* sphinxcontrib-actdiag
I also needed to install sphinxcontrib-manpage

2017-05-03 06:56 UTC, breakreturn commented on README.md
> +* sphinxcontrib-actdiag
True. Will fix.

2017-05-03 06:59 UTC, erikboto commented on README.md
> +* sphinxcontrib-actdiag
Oh, and I needed texlive-latex-base (on Debian) for pdflatex which is used for generating PDFs

2017-05-03 07:03 UTC, frznlogic approved these changes

2017-05-03 07:05 UTC, frznlogic commented
Your argument makes sense regarding build environment @breakreturn . If we see a need for it in the future ti can be added.

2017-05-03 07:47 UTC, erikboto approved these changes

2017-05-03 10:46 UTC, merged