Semi-revert Vagrant => Docker
Pelagicore/software-factory pull request #101
Opened 2018-01-26 09:21 UTC by tobsan

There were CI issues with using only Docker in Jenkins, so we're moving
back to using Vagrant for provisioning.

Wait until [pelux-manifests/118](https://github.com/Pelagicore/pelux-manifests/pull/118) is merged.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

2018-01-26 09:44 UTC, thenor approved these changes

2018-01-29 17:00 UTC, DunderRoffe requested changes
Looks good but the commit message is really confusing. Is it reverting from Vagrant to Docker or is it reverting the commit that changed from Vagrant to Docker?
Feels like a double negative or something.

2018-01-29 17:01 UTC, DunderRoffe commented
If we are reverting in git terms I think we should refer to the SHA1 of the commit we are reverting relative to

2018-01-30 10:30 UTC, jonte approved these changes

2018-01-31 09:09 UTC, tobsan commented
@DunderRoffe we are not reverting in git terms, more in logical terms. When changing the SWF to describe Vagrant => Docker, there were structural changes made as well. Only the vagrant/docker part is "reverted" here.

2018-02-01 07:53 UTC, DunderRoffe approved these changes
I still think that the commit message should be revised for clarity as we wont know what this means in one year.

But at the same time I should not be blocking on this so if you think it is redundant I'm fine with merging.

2018-02-05 14:01 UTC, merged