Add info on where to find image
Pelagicore/software-factory pull request #11
Opened 2017-06-02 12:50 UTC by zeenix

NOTE: this is on top of https://github.com/Pelagicore/software-factory/pull/10

2017-06-02 12:57 UTC, jonte requested changes

2017-06-02 12:57 UTC, jonte commented on docs/chapters/baseplatform/obtaining-a-PELUX-release.rst
> +When done fetching the sources, create a build directory and set up bitbake. TEMPLATECONF tells the `oe-init-build-env` script which path to fetch configuration samples from.
Backticks for TEMPLATECONF

2017-06-02 12:57 UTC, jonte commented on docs/chapters/baseplatform/obtaining-a-PELUX-release.rst
> +The script will create configs if there are no configs present, a message about created `conf/local.conf` and `conf/bblayers.conf` files is normal.
Double backticks for paths

2017-06-02 12:57 UTC, jonte commented on docs/chapters/baseplatform/obtaining-a-PELUX-release.rst
> +When the build is complete the result will be available in `tmp/deploy/images/<machine>/`. It is possible to generate a number of different image formats, ranging from just the rootfs as a tarball to
Double backticks for paths

2017-06-02 12:57 UTC, jonte commented on docs/chapters/baseplatform/obtaining-a-PELUX-release.rst
> +When done fetching the sources, create a build directory and set up bitbake. TEMPLATECONF tells the `oe-init-build-env` script which path to fetch configuration samples from.
and oe-init-build..

2017-06-02 14:19 UTC, zeenix commented on docs/chapters/baseplatform/obtaining-a-PELUX-release.rst
> +The script will create configs if there are no configs present, a message about created `conf/local.conf` and `conf/bblayers.conf` files is normal.
You reviewed changes from other PR that this PR is based on and that PR is already merged, so I'll add additional patch and when i push the weird situation of having other PR's patches here would also be automatically resolved. Github should have some infra for a PR being based on another one, or does it already?

2017-06-05 06:00 UTC, breakreturn approved these changes

2017-06-05 09:59 UTC, jonte approved these changes

2017-06-05 10:01 UTC, merged