swupdate: add swupdate info for intel NUC
Pelagicore/software-factory pull request #123
Opened 2018-06-25 11:20 UTC by TSAnsari

Signed-off-by: Tariq Ansari <tansari@luxoft.com>

2018-06-25 11:24 UTC, sashko commented on docs/chapters/architecture/SOTA-system.rst
> +    For intel-nuc:
it's either the target name, either Intel NUC

2018-06-25 20:25 UTC, FlorentRevest approved these changes

2018-06-26 10:13 UTC, sashko commented on docs/chapters/architecture/SOTA-system.rst
> +    For raspberrypi3:
perhaps we should unify it? :)

2018-06-26 10:36 UTC, TSAnsari commented on docs/chapters/architecture/SOTA-system.rst
> +    For raspberrypi3:
Unification done. Please have a look

2018-06-27 14:13 UTC, sashko requested changes

2018-06-27 14:13 UTC, sashko commented on docs/chapters/architecture/SOTA-system.rst
> +- A raspberrypi3 or an Intel NUC(intel-corei7-64) running PELUX. Other
space before (

2018-06-27 15:08 UTC, TSAnsari commented
fixed the space

2018-06-27 15:57 UTC, sashko approved these changes

2018-06-27 19:05 UTC, merged