Fixing typos, adding information and updating submodule
Pelagicore/software-factory pull request #124
Opened 2018-06-27 14:11 UTC by fhajredini

2018-06-27 14:12 UTC, sashko requested changes
fix commit messages titles, please

2018-06-27 14:23 UTC, fhajredini commented
Fixed it. Left out spelling and typos because its too general. Let me know if you think otherwise. @sashko

2018-06-27 14:29 UTC, sashko approved these changes

2018-06-28 10:18 UTC, thenor approved these changes

2018-06-28 10:30 UTC, merged