README.md: Add build deps install instructions
Pelagicore/software-factory pull request #18
Opened 2017-06-14 13:25 UTC by GordanM

2017-06-14 13:27 UTC, zeenix requested changes

2017-06-14 13:27 UTC, zeenix commented on README.md
> +              sphinxcontrib-manpage
is the pip really needed here? I mean if all packages are available on debian, best just have 1 command?

2017-06-15 09:02 UTC, GordanM commented on README.md
> +              sphinxcontrib-manpage
I think these packages are available only through pip. 

I tried `ap-get`-ing them and it didn't work. Maybe @breakreturn knows the details.

2017-06-15 09:36 UTC, DunderRoffe commented on README.md
> +              sphinxcontrib-manpage
Yes they are available through apt in debian, at least in debian 9. However, we still have to use pip in other places, for instance vagrant-cookbook, to install packages that are not available through apt so in the interest of consistency we should use pip to install python packages even in this case. Furthermore, pip will provide you with a more up to date version.

2017-06-15 11:02 UTC, rpannek approved these changes

2017-06-15 11:06 UTC, zeenix commented on README.md
> +              sphinxcontrib-manpage
hmm.. ok. I just thought one command instead of two separate ones, would be simpler.

2017-06-15 11:07 UTC, zeenix approved these changes

2017-06-18 14:01 UTC, breakreturn commented on README.md
> +              sphinxcontrib-manpage
@GordanM No I don't know any details. I can only remember using pip before for these packages. I have no real opinion here, whatever instructions that would work for most users is the best I'd say.

2017-06-18 14:01 UTC, breakreturn approved these changes

2017-06-19 08:07 UTC, GordanM commented on README.md
> +              sphinxcontrib-manpage
Thanks for the comments!

2017-06-19 08:07 UTC, merged