git-workflow: Add info on good commits
Pelagicore/software-factory pull request #25
Opened 2017-07-18 13:35 UTC by zeenix

2017-07-18 13:44 UTC, GordanM approved these changes

2017-07-18 13:50 UTC, rpannek approved these changes

2017-07-25 06:22 UTC, DunderRoffe requested changes

2017-07-25 06:22 UTC, DunderRoffe commented on docs/chapters/workflow/git-workflow.rst
> +#. has a good commit message associated with it.
There needs to be an explanation or at least a link to an explanation of what we believe a good commit message is. Furthermore, a good commit message is a bit to vague. We have rules of which some are not trivial which contributors never will guess on their own.

2017-07-25 06:27 UTC, DunderRoffe commented on docs/chapters/workflow/git-workflow.rst
> +#. has a good commit message associated with it.
OK saw that you have a link below. However, that is not clear and I stand by my point that the above line is confusing without any description of what a good commit message is. Good commit implies good commit message sounds awfully trivial

2017-07-26 10:44 UTC, zeenix commented on docs/chapters/workflow/git-workflow.rst
> +#. has a good commit message associated with it.
The rationale below gives a good (even though vague) guideline on what a good commit message would be. For more specific example, readers can follow the link provided.

2017-07-26 11:25 UTC, DunderRoffe approved these changes
Well I guess it is good enough...

2017-08-10 14:28 UTC, merged