baseplatform: Add section on creating a manifest
Pelagicore/software-factory pull request #30
Opened 2017-08-11 12:53 UTC by jonte

2017-08-11 13:12 UTC, breakreturn requested changes
Tiniest comment only

2017-08-11 13:12 UTC, breakreturn commented on docs/chapters/baseplatform/creating-a-manifest.rst
> +* The ``xml`` files in the repository are the actual manifest files. The manifest files in the repository must be modified to indicatethe correct repositories. It is common to structure the manifets
"indicatethe" -> indicate the

2017-08-11 13:13 UTC, breakreturn commented
Feel free to merge it after adding the space between the two words i commented on.

2017-08-14 12:09 UTC, jonte commented
Typo fixed. Thanks for the review. Merging.

2017-08-14 12:09 UTC, merged