Restructure the index files and add CI articles
Pelagicore/software-factory pull request #40
Opened 2017-10-09 13:55 UTC by rpannek

After the resturturing work in the blueprint it is now easier to
use it in a project. This patch changes some of the index files
so they would not use include anymore but toctrees instead.

It also adds some articles from the blueprint like those about the
CI and the blueprint itself.

2017-10-09 15:05 UTC, demonicblue commented on docs/chapters/baseplatform/index.rst
> +   ../../swf-blueprint/docs/articles/variant-concept-in-yocto
This line generates a warning in sphinx. The document doesn't exist in the specified path.
Should be
../../swf-blueprint/docs/articles/baseplatform/variant-concept-in-yocto

2017-10-09 15:20 UTC, mardy requested changes

2017-10-09 15:20 UTC, mardy commented on docs/chapters/baseplatform/building-PELUX-sources.rst
> +This chapter details how to download and configure the sources of an PELUX build, so
an -> a

2017-10-09 15:54 UTC, rpannek commented
Fixed those two typos.

2017-10-10 07:17 UTC, tobsan approved these changes
Looks good!

2017-10-10 07:17 UTC, tobsan commented on docs/index.rst
> +The Software Factory documentation is the central space where we collect all useful information on how to work within the project.
This line looks long.

2017-10-10 07:53 UTC, breakreturn approved these changes

2017-10-10 07:54 UTC, breakreturn commented
Given that @mardy had a comment on typo which is fixed, I'll merge this even if the comment isn't resolved technically.

2017-10-10 07:54 UTC, merged