WIP architecture: Add SOTA chapters
Pelagicore/software-factory pull request #80
Opened 2018-01-02 14:05 UTC by GordanM

This commit adds chapters for the specific SOTA client used in the
PELUX Platform Baseline. Additional chapters about the generic
research, requirements and use cases is added through the SWF
blueprint.

Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

2018-01-02 14:30 UTC, tobsan requested changes
I suppose you want to bump the blueprint once that PR has been merged also, but looks good overall imho.

2018-01-02 14:30 UTC, tobsan commented on docs/chapters/architecture/index.rst
> +   ../../swf-blueprint/docs/articles/architecture//arch-vertical-configurations.rst
extra / here

2018-01-02 14:33 UTC, GordanM commented
Depends on: https://github.com/Pelagicore/software-factory-blueprint/pull/70

2018-01-03 08:27 UTC, GordanM commented
@tobsan  I have updated the submodule.

2018-01-03 09:28 UTC, tobsan approved these changes

2018-01-03 09:36 UTC, merged