Add SDK entry point
Pelagicore/software-factory pull request #9
Opened 2017-06-01 14:43 UTC by zeenix

Add a section for service developers to obtain the SDK from. For now we
just introduce SDK and where to get it. Also the link to downloads is
bogus until we the website setup and our first release done.
---

Is this what we are looking for?

2017-06-01 15:16 UTC, rpannek requested changes

2017-06-01 15:16 UTC, rpannek commented on docs/chapters/sdk/index.rst
> +PELUX provides a Software Development Kit (SDK), for quick and easy development of software components for a PELUX (or PELUX-based) system. The SDK installer script can be downloaded from `PELUX webs
Perhaps add some info about who the audience of such a SDK would be?

2017-06-01 16:43 UTC, zeenix commented
How is it now @rpannek ?

2017-06-02 07:35 UTC, rpannek approved these changes

2017-06-02 07:35 UTC, rpannek commented
Nice, looks good now.

2017-06-02 08:19 UTC, breakreturn approved these changes

2017-06-02 08:20 UTC, merged